metagenome-atlas/atlas

- atlas/conf.py
Add the contaminant references to the config file
> Add contaminant_references to config

- README.md
- README.rst
I think a picture is the best explanation what Atlas is.
> Add workflow image to the readme

- atlas/rules/assemble.snakefile
> changed bug in merge error input

- atlas/rules/assemble.snakefile
> corrected a bug in read_Stats

- atlas/rules/assemble.snakefile
This created a bug on the cluster.
>  added memopry limit to samtools

- atlas/Snakefile
> add bash interpreter

- atlas/rules/assemble.snakefile
removed inverleaved stub.
bbnorm keword changed, apparently.
> target depth keyword changed

- atlas/rules/assemble.snakefile
Split pre-filter alignment and pileup in two.
For me this rule was quite time-consuming, so I prefer to split it in two.
> Better allignments

- atlas/__init__.py
- atlas/envs/DASTool.yaml
- atlas/rules/gene_annotation.snakefile
- atlas/rules/genecatalog.snakefile
Egg Nogg annotates now the gene catalog. 
using `atlas assemble `
> Annotation

- .circleci/config.yml
- README.md
- atlas/__init__.py
- atlas/envs/DASTool.yaml
- atlas/envs/canopy.yaml
- atlas/envs/cat.yaml
- atlas/envs/cd-hit.yaml
- atlas/envs/checkm.yaml
- atlas/envs/concoct.yaml
- atlas/envs/dRep.yaml
- atlas/envs/eggNOG.yaml
- atlas/envs/maxbin.yaml
- atlas/envs/metabat.yaml
- atlas/envs/mmseqs.yaml
- atlas/envs/optional_genome_binning.yaml
- atlas/envs/prokka.yaml
- atlas/envs/report.yaml
- atlas/envs/required_packages.yaml
- atlas/envs/sequence_utils.yaml
- atlas/envs/tree.yaml
- atlas/rules/download.snakefile
This change should not have an inpact on the atlas at running, but may be all environements need to be recreated. 
- conda-forge before bioconda. 
- r is part of defaults
> change order of bioconda channels

- atlas/scripts/utils/tree.py
@jmtsuji Could you please test the branch tree. And see if it solves your problem?
> Fixes #233

- CONTRIBUTING.md
- atlas/rules/binning.snakefile
- atlas/rules/cat_taxonomy.smk
- atlas/rules/genomes.smk
- atlas/rules/predict_genes_of_genomes.py
renames checkm results for representatives genomes instead of re-running them.
> Solvecheckpoints

- atlas/rules/genomes.smk
- atlas/rules/predict_genes_of_genomes.py
> predict genes in parallel

- atlas/rules/genecatalog.snakefile
> mmseq with many subset databases

- docs/usage/cluster.rst
> Light proofing of cluster instructions

- .circleci/config.yml
- atlas/__init__.py
- atlas/envs/gtdbtk.yaml
- atlas/rules/download.snakefile
> updae to new GTDB

- atlas/__init__.py
- atlas/envs/gtdbtk.yaml
- atlas/rules/download.snakefile
> Update GTDB to V1.5

- atlas/envs/dRep.yaml
- atlas/rules/genomes.smk
- atlas/rules/rename_genomes.py
> new drep version

- atlas/rules/crossbining.smk
fix conflcts caused by ambiguous wildcards
> simple bugs fix

- atlas/workflow/rules/dram.smk
- atlas/workflow/rules/sra.smk
standardization of logs folders
> log/ to logs/

- atlas/workflow/envs/dram.yaml
- atlas/workflow/scripts/DRAM_get_all_modules.py
Linked. to #506 
To use this branch follow the steps explained in https://metagenome-atlas.readthedocs.io/en/latest/usage/getting_started.html#install-metagenome-atlas-from-github
And use the branch `dram13`
> update dram to v 1.3

- atlas/template_config.yaml
- atlas/workflow/Snakefile
- atlas/workflow/config/default_config.yaml
- atlas/workflow/rules/genomes.smk
- atlas/workflow/rules/qc.smk
- atlas/workflow/scripts/filter_genomes.py
- atlas/workflow/scripts/utils/genome_stats.py
- atlas/workflow/scripts/utils/io.py
- atlas/workflow/scripts/utils/parsers_checkm.py
galah doesn't a good job at filtering genomes
> filter genomes my self

- atlas/workflow/Snakefile
- atlas/workflow/envs/hdf.yaml
- atlas/workflow/rules/genecatalog.smk
- atlas/workflow/rules/gtdbtk.smk
- atlas/workflow/scripts/combine_gene_coverages.py
- docs/usage/output.rst
HDF is a more efficient storage than the parquet for this very large data.
> Use hdfs for gene catalogs

- atlas/atlas.py
- atlas/init/create_sample_table.py
- atlas/init/parse_sra.py
- docs/usage/configuration.rst
- docs/usage/getting_started.rst
- workflow/report/template_QC_report.html
- workflow/report/template_assembly_report.html
- workflow/report/template_bin_report.html
- workflow/rules/binning.smk
- workflow/scripts/parse_vamb.py
- workflow/scripts/utils/io.py
Hi @SilasK 
I hope it doesn't come across as too petty, but I have corrected a few spelling mistakes.
Best wishes
Silvio
> Correction of typos
